"""Lotus CLI — AI Dev Team bootstrap and management."""

import shutil
import subprocess
import sys
from pathlib import Path

import click
import yaml
from jinja2 import Environment, PackageLoader

from lotus.repo import get_repo_info, RepoInfo

jinja_env = Environment(
    loader=PackageLoader("lotus", "scaffolds"),
    keep_trailing_newline=True,
)

LABELS = [
    ("lotus:feature", "0E8A16", "Feature for Lotus agent"),
    ("lotus:bugfix", "D93F0B", "Bug fix for Lotus agent"),
    ("lotus:refactor", "1D76DB", "Refactor for Lotus agent"),
    ("lotus:chore", "FBCA04", "Maintenance task for Lotus agent"),
    ("lotus:queued", "C5DEF5", "Queued for agent processing"),
    ("lotus:needs-human", "B60205", "Agent failed, needs human help"),
    ("lotus:ai-generated", "BFD4F2", "PR generated by Lotus agent"),
    ("lotus:ready", "0E8A16", "PR ready to merge"),
]


@click.group()
@click.version_option(version="0.1.0")
def cli():
    """Lotus — AI Dev Team."""


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# lotus doctor
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@cli.command()
def doctor():
    """Check prerequisites for Lotus."""
    ok = True

    # Python version
    v = sys.version_info
    if v >= (3, 11):
        click.echo(f"✓ Python {v.major}.{v.minor}.{v.micro}")
    else:
        click.echo(f"✗ Python {v.major}.{v.minor} (need >= 3.11)")
        ok = False

    # git
    if _cmd_exists("git"):
        click.echo("✓ git")
    else:
        click.echo("✗ git not found")
        ok = False

    # gh CLI
    if _cmd_exists("gh"):
        auth = subprocess.run(
            ["gh", "auth", "status"],
            capture_output=True,
        )
        if auth.returncode == 0:
            click.echo("✓ gh CLI (authenticated)")
        else:
            click.echo("✗ gh CLI installed but not authenticated (run: gh auth login)")
            ok = False
    else:
        click.echo("✗ gh CLI not found (https://cli.github.com/)")
        ok = False

    # Git remote
    try:
        repo = get_repo_info()
        click.echo(f"✓ GitHub repo: {repo.full_name}")
        if repo.has_commits:
            click.echo(f"✓ Branch: {repo.default_branch} (has commits)")
        else:
            click.echo("⚠ No commits yet. Run: git commit --allow-empty -m 'init'")
    except RuntimeError as e:
        click.echo(f"✗ {e}")
        ok = False

    # npm (for Claude Code install in Actions)
    if _cmd_exists("npm"):
        click.echo("✓ npm (for local Claude Code testing)")
    else:
        click.echo("⚠ npm not found (optional — needed for local agent testing)")

    if ok:
        click.echo("\n✓ All checks passed. Ready to run: lotus init")
    else:
        click.echo("\n✗ Fix the issues above before running lotus init.")
    return ok


def _cmd_exists(cmd: str) -> bool:
    return shutil.which(cmd) is not None


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# lotus init
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@cli.command()
@click.option(
    "--language",
    type=click.Choice(["python", "typescript", "rust", "go"]),
    prompt=True,
)
@click.option("--test-cmd", prompt="Test command")
@click.option("--lint-cmd", prompt="Lint command")
@click.option("--format-cmd", prompt="Format command")
@click.option(
    "--typecheck-cmd",
    prompt="Typecheck command (or 'none')",
    default="none",
)
def init(language, test_cmd, lint_cmd, format_cmd, typecheck_cmd):
    """Initialize Lotus in the current repository."""
    # Pre-flight
    try:
        repo = get_repo_info()
    except RuntimeError as e:
        click.echo(f"Error: {e}")
        click.echo("Run 'lotus doctor' to check prerequisites.")
        raise SystemExit(1)

    if not repo.has_commits:
        click.echo("Error: Repo has no commits. Run:")
        click.echo("  git commit --allow-empty -m 'init' && git push")
        raise SystemExit(1)

    click.echo(f"\n=== Initializing Lotus for {repo.full_name} ===\n")

    repo_root = Path.cwd()
    github_user = repo.owner

    config = {
        "project": {
            "name": repo.name,
            "language": language,
        },
        "commands": {
            "test": test_cmd,
            "lint": lint_cmd,
            "format": format_cmd,
            "typecheck": typecheck_cmd if typecheck_cmd != "none" else None,
        },
        "agents": {
            "max_concurrent": 2,
            "max_retries": 3,
            "max_heal_attempts": 2,
            "timeout_minutes": 30,
            "max_turns": 50,
            "claude_code_version": "latest",
        },
        "ci": {
            "auto_merge": False,
            "required_checks": ["test", "lint", "format"],
        },
        "issue_types": {
            "feature": {
                "label": "lotus:feature",
                "prompt": "prompts/feature.md",
                "post_check": "feature",
                "branch_prefix": "feat",
                "commit_prefix": "feat",
            },
            "bugfix": {
                "label": "lotus:bugfix",
                "prompt": "prompts/bugfix.md",
                "post_check": "bugfix",
                "branch_prefix": "fix",
                "commit_prefix": "fix",
            },
            "refactor": {
                "label": "lotus:refactor",
                "prompt": "prompts/refactor.md",
                "post_check": "refactor",
                "branch_prefix": "refactor",
                "commit_prefix": "refactor",
            },
            "chore": {
                "label": "lotus:chore",
                "prompt": "prompts/chore.md",
                "post_check": "chore",
                "branch_prefix": "chore",
                "commit_prefix": "chore",
            },
        },
    }

    ctx = {
        **config,
        "github_user": github_user,
        "repo": repo,
    }

    # ── Create directories ──
    dirs = [
        ".lotus/prompts",
        ".lotus/memory/modules",
        ".lotus/post-checks",
        ".github/workflows",
        ".github/actions/setup-env",
        ".github/ISSUE_TEMPLATE",
    ]
    for d in dirs:
        (repo_root / d).mkdir(parents=True, exist_ok=True)

    # ── Write config ──
    config_path = repo_root / ".lotus" / "config.yml"
    config_path.write_text(yaml.dump(config, default_flow_style=False, sort_keys=False))
    click.echo(f"  wrote {config_path}")

    # ── Render Jinja templates ──
    jinja_templates = {
        "prompts/system.md.j2": ".lotus/prompts/system.md",
        "workflows/ci.yml.j2": ".github/workflows/ci.yml",
        "workflows/agent-dispatch.yml.j2": ".github/workflows/agent-dispatch.yml",
        "workflows/agent-heal.yml.j2": ".github/workflows/agent-heal.yml",
        "workflows/queue-drain.yml.j2": ".github/workflows/queue-drain.yml",
        "workflows/stale-cleanup.yml.j2": ".github/workflows/stale-cleanup.yml",
        "actions/setup-env/action.yml.j2": ".github/actions/setup-env/action.yml",
        "memory/PROJECT.md.j2": ".lotus/memory/PROJECT.md",
        "memory/DECISIONS.md.j2": ".lotus/memory/DECISIONS.md",
        "CODEOWNERS.j2": ".github/CODEOWNERS",
        "Dockerfile.agent.j2": "Dockerfile.agent",
    }
    for template_name, output_path in jinja_templates.items():
        tmpl = jinja_env.get_template(template_name)
        output = repo_root / output_path
        output.write_text(tmpl.render(**ctx))
        click.echo(f"  wrote {output}")

    # ── Copy static files (no Jinja rendering) ──
    static_files = {
        "prompts/feature.md": ".lotus/prompts/feature.md",
        "prompts/bugfix.md": ".lotus/prompts/bugfix.md",
        "prompts/refactor.md": ".lotus/prompts/refactor.md",
        "prompts/chore.md": ".lotus/prompts/chore.md",
        "prompts/heal.md": ".lotus/prompts/heal.md",
        "issue_templates/feature.yml": ".github/ISSUE_TEMPLATE/feature.yml",
        "issue_templates/bug.yml": ".github/ISSUE_TEMPLATE/bug.yml",
        "issue_templates/refactor.yml": ".github/ISSUE_TEMPLATE/refactor.yml",
        "issue_templates/chore.yml": ".github/ISSUE_TEMPLATE/chore.yml",
        # Standalone scripts (no lotus imports, run in target repo)
        "standalone/validate.py": ".lotus/validate.py",
        "standalone/post_checks/feature.py": ".lotus/post-checks/feature.py",
        "standalone/post_checks/bugfix.py": ".lotus/post-checks/bugfix.py",
        "standalone/post_checks/refactor.py": ".lotus/post-checks/refactor.py",
        "standalone/post_checks/chore.py": ".lotus/post-checks/chore.py",
    }
    for src_name, dest_path in static_files.items():
        src = Path(__file__).parent / "scaffolds" / src_name
        dest = repo_root / dest_path
        shutil.copy2(src, dest)
        click.echo(f"  wrote {dest}")

    # ── Create GitHub labels ──
    click.echo("\nCreating GitHub labels...")
    _create_labels()

    # ── Commit and push generated files before branch protection is applied ──
    click.echo("\nPushing generated files...")
    push_result = subprocess.run(
        'git add -A && git commit -m "chore: initialize Lotus" && git push',
        shell=True,
        capture_output=True,
        text=True,
    )
    if push_result.returncode == 0:
        click.echo("  ✓ Files committed and pushed")
    else:
        click.echo(f"  ⚠ Push failed: {push_result.stderr.strip()}")
        click.echo(
            "    Commit and push manually before branch protection takes effect."
        )

    # ── Configure branch protection ──
    click.echo("Configuring branch protection...")
    _configure_branch_protection(config, repo)

    # ── Print next steps ──
    click.echo("\n✓ Lotus initialized.\n")
    click.echo("Required secrets (run these now):")
    click.echo("  gh secret set ANTHROPIC_API_KEY")
    click.echo("  gh secret set LOTUS_BOT_TOKEN")
    click.echo("")
    click.echo("To create LOTUS_BOT_TOKEN:")
    click.echo(
        "  https://github.com/settings/personal-access-tokens/new"
        "?repository_ids=&scopes=contents:write,issues:write,"
        "pull_requests:write,metadata:read"
    )
    click.echo("  Select: Only select repositories → your repo")
    click.echo(
        "  Permissions: Contents (R+W), Issues (R+W), Pull requests (R+W), Metadata (R)"
    )
    click.echo("")
    click.echo("Create your first issue using the Lotus templates in GitHub.")


def _create_labels():
    """Create all lotus:* labels in the GitHub repo."""
    for name, color, description in LABELS:
        result = subprocess.run(
            [
                "gh",
                "label",
                "create",
                name,
                "--color",
                color,
                "--description",
                description,
                "--force",
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            click.echo(f"  ✓ {name}")
        else:
            click.echo(f"  ⚠ {name}: {result.stderr.strip()}")


def _configure_branch_protection(config: dict, repo: RepoInfo):
    """Set branch protection rules via gh CLI."""
    import json

    protection = {
        "required_status_checks": {
            "strict": True,
            "contexts": config["ci"]["required_checks"],
        },
        "enforce_admins": True,
        "required_pull_request_reviews": None,
        "restrictions": None,
    }
    result = subprocess.run(
        [
            "gh",
            "api",
            f"repos/{repo.full_name}/branches/{repo.default_branch}/protection",
            "--method",
            "PUT",
            "--input",
            "-",
        ],
        input=json.dumps(protection),
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        click.echo("  ✓ Branch protection configured")
    else:
        click.echo(f"  ⚠ Branch protection failed: {result.stderr.strip()}")
        click.echo("    This may require a Pro/Team plan. Set manually if needed.")

    if config["ci"]["auto_merge"]:
        subprocess.run(
            ["gh", "repo", "edit", "--enable-auto-merge"],
            capture_output=True,
        )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# lotus status
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@cli.command()
def status():
    """Show Lotus status: active agents, queue, recent PRs."""
    try:
        sections = {
            "Active agents": (
                [
                    "gh",
                    "run",
                    "list",
                    "--workflow=agent-dispatch.yml",
                    "--status=in_progress",
                    "--json",
                    "headBranch,startedAt",
                ],
                lambda r: f"  → {r['headBranch']} (started {r['startedAt']})",
            ),
            "Queued issues": (
                [
                    "gh",
                    "issue",
                    "list",
                    "--label",
                    "lotus:queued",
                    "--json",
                    "number,title",
                ],
                lambda r: f"  → #{r['number']}: {r['title']}",
            ),
            "Open AI PRs": (
                [
                    "gh",
                    "pr",
                    "list",
                    "--label",
                    "lotus:ai-generated",
                    "--json",
                    "number,title,headRefName",
                ],
                lambda r: f"  → #{r['number']}: {r['title']} ({r['headRefName']})",
            ),
            "Needs human help": (
                [
                    "gh",
                    "issue",
                    "list",
                    "--label",
                    "lotus:needs-human",
                    "--json",
                    "number,title",
                ],
                lambda r: f"  → #{r['number']}: {r['title']}",
            ),
        }

        click.echo("=== Lotus Status ===\n")
        for label, (cmd, fmt) in sections.items():
            try:
                result = subprocess.run(cmd, capture_output=True, text=True, check=True)
                items = yaml.safe_load(result.stdout) or []
                click.echo(f"{label}: {len(items)}")
                for item in items:
                    click.echo(fmt(item))
            except FileNotFoundError:
                click.echo(f"{label}: (gh CLI not found)")
            except subprocess.CalledProcessError as e:
                stderr = e.stderr.strip()
                msg = stderr.splitlines()[0] if stderr else "gh command failed"
                click.echo(f"{label}: (error — {msg})")
            click.echo()

    except Exception as e:
        click.echo(f"Error: {e}")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# lotus compact
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@cli.command()
def compact():
    """Compact memory files (summarize + deduplicate via Claude)."""
    click.echo("Phase 4 — not yet implemented.")
    click.echo("Will use claude CLI to rewrite memory files, removing")
    click.echo("duplicates, resolving contradictions, and condensing entries.")


if __name__ == "__main__":
    cli()
